/*
 * Copyright 2025 TASKEXPOSURE
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, Input, ElementRef, ViewChild, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ToastService } from '../../../core/services/toast.service';

@Component({
  selector: 'app-share-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './share-card.component.html',
  styleUrl: './share-card.component.scss',
})
export class ShareCardComponent {
  @Input() score: number = 0;
  @Input() highExposureTasks: string[] = [];
  @Input() topAction: string = '';

  @ViewChild('cardElement') cardElement!: ElementRef<HTMLDivElement>;

  private toast = inject(ToastService);

  get scoreColorClass(): string {
    if (this.score <= 33) return 'low';
    if (this.score <= 66) return 'medium';
    return 'high';
  }

  get scoreLabel(): string {
    if (this.score <= 33) return 'Low Exposure';
    if (this.score <= 66) return 'Moderate Exposure';
    return 'High Exposure';
  }

  get linkedInShareUrl(): string {
    const text = encodeURIComponent(
      `I just assessed my AI exposure with TASKEXPOSURE. My score: ${this.score}% (${this.scoreLabel}). Understanding where AI impacts my work helps me focus on what matters.\n\n#AI #CareerDevelopment #FutureOfWork`
    );
    return `https://www.linkedin.com/sharing/share-offsite/?text=${text}`;
  }

  get twitterShareUrl(): string {
    const text = encodeURIComponent(
      `My AI exposure score: ${this.score}% (${this.scoreLabel}). Assessed with @TASKEXPOSURE. #AI #FutureOfWork`
    );
    return `https://twitter.com/intent/tweet?text=${text}`;
  }

  async downloadAsImage(): Promise<void> {
    try {
      // For production, we'd use html2canvas here
      // For now, we'll create a simple text-based download
      const content = this.generateTextReport();
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);

      const a = document.createElement('a');
      a.href = url;
      a.download = `taskexposure-report-${this.score}pct.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      this.toast.success('Report downloaded successfully');
    } catch (error) {
      this.toast.error('Failed to download report');
      console.error('Download error:', error);
    }
  }

  copyToClipboard(): void {
    const text = `My AI Exposure Score: ${this.score}% (${this.scoreLabel})\n\nAssessed with TASKEXPOSURE - Understanding my career's relationship with AI automation.`;

    navigator.clipboard.writeText(text).then(
      () => this.toast.success('Copied to clipboard'),
      () => this.toast.error('Failed to copy')
    );
  }

  shareToLinkedIn(): void {
    window.open(this.linkedInShareUrl, '_blank', 'width=600,height=600');
  }

  shareToTwitter(): void {
    window.open(this.twitterShareUrl, '_blank', 'width=600,height=400');
  }

  private generateTextReport(): string {
    return `
═══════════════════════════════════════════════════
               TASKEXPOSURE REPORT
═══════════════════════════════════════════════════

AI EXPOSURE SCORE: ${this.score}%
RISK LEVEL: ${this.scoreLabel}

───────────────────────────────────────────────────
HIGH EXPOSURE TASKS
───────────────────────────────────────────────────
${this.highExposureTasks.map((task, i) => `${i + 1}. ${task}`).join('\n') || 'No high exposure tasks identified'}

───────────────────────────────────────────────────
RECOMMENDED ACTION
───────────────────────────────────────────────────
${this.topAction || 'Continue monitoring your task exposure'}

═══════════════════════════════════════════════════
Generated by TASKEXPOSURE
${new Date().toLocaleDateString()}
═══════════════════════════════════════════════════
`.trim();
  }
}
